# Generated by Django 3.1.5 on 2021-01-25 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_activelistings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activelistings',
            old_name='startingbid',
            new_name='startingBid',
        ),
    ]
