# Generated by Django 3.1.5 on 2021-01-25 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20210125_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activelistings',
            name='category',
            field=models.CharField(max_length=64),
        ),
    ]
