# Generated by Django 3.1.5 on 2021-01-25 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20210125_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='Category',
        ),
        migrations.AddField(
            model_name='categories',
            name='newcategory',
            field=models.CharField(default='uncategorized', max_length=64),
        ),
    ]
