# Generated by Django 3.1.5 on 2021-01-25 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20210125_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='newcategory',
        ),
        migrations.AddField(
            model_name='categories',
            name='category',
            field=models.CharField(default='', max_length=64),
        ),
    ]
