# Generated by Django 3.1.5 on 2021-01-26 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20210125_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activelistings',
            name='imageurl',
            field=models.URLField(blank=True, null=True),
        ),
    ]
