# Generated by Django 3.1.5 on 2021-01-28 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_auto_20210128_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activelistings',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categorylistings', to='auctions.categories'),
        ),
    ]
