# Generated by Django 3.1.5 on 2021-01-29 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_auto_20210128_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='savedlistings',
            field=models.ManyToManyField(blank=True, related_name='userswhosaved', to='auctions.activelistings'),
        ),
        migrations.AlterField(
            model_name='bids',
            name='biddinguser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userbid', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bids',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listingbid', to='auctions.activelistings'),
        ),
    ]
