# Generated by Django 3.1.5 on 2021-01-31 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_auto_20210129_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='activelistings',
            name='status',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
