# Generated by Django 3.1.5 on 2021-01-31 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_activelistings_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activelistings',
            name='status',
            field=models.CharField(blank=True, default='active', max_length=10, null=True),
        ),
    ]
