# Generated by Django 3.1.5 on 2021-01-31 07:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0020_auto_20210131_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='activelistings',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='createdlistings', to=settings.AUTH_USER_MODEL),
        ),
    ]
